
name: Build uLaunch

on: [push]
jobs:
  uLaunch:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v3
    - name: Update repository
      run: |
        git submodule update --init --recursive
    
    - name: Prepare master libnx
      run: |
        git clone https://github.com/switchbrew/libnx
        make -C libnx/
        cp -r libnx/nx/external/bsd/include libnx/nx
    
    - name: Compile
      run: |
        make -j$(nproc) LIBNX=$PWD/libnx/nx/
        zip -r SdOut.zip SdOut
        
    - uses: actions/upload-artifact@master
      with:
        name: SdOut
        path: SdOut.zip
